[2024-07-08T17:18:22.560+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-20T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
